Check arguments.

diff --git a/.github/workflows/site-checks.yml b/.github/workflows/site-checks.yml
--- a/.github/workflows/site-checks.yml
+++ b/.github/workflows/site-checks.yml
@@ -23,13 +23,13 @@ jobs:
     - name: Check websocket connection
       run: |
         #/usr/local/bin/wscat --version
-        sudo npm i wscat
+        sudo npm i wscatsd
         wscat --version
-        wscat --connect --help "wss://reanimate.clozecards.com:443/ws/"
-    - name: Check links at reanimate.github.io
-      run: |
-        checklink --quiet --broken "https://reanimate.github.io/" > failures.txt
-        if [ -s failures.txt ]; then
-          cat failures.txt
-          exit 1
-        fi
+        wscat --help --connect "wss://reanimate.clozecards.com:443/ws/"
+    # - name: Check links at reanimate.github.io
+    #   run: |
+    #     checklink --quiet --broken "https://reanimate.github.io/" > failures.txt
+    #     if [ -s failures.txt ]; then
+    #       cat failures.txt
+    #       exit 1
+    #     fi
